### ISSUE TITLE
Bot panel list window gone. 

### ISSUE THREAD

**Issue by Groundzerowin** [ike3/mangosbot-addon#7]
I accidentally right clicked on the bot list panel window and now it’s gone from the screen.  I’ve deleted and downloaded and added the addon again. Still cannot being up the panel to tell my bots what to do.   

How do I get the panel back?

**Comment by RavingSmurfGB** [comment]
For future referance

If the gui/panel does not come up for you after typing /bot
- Navigate to your WoW folder
- Under WTF > Account > "Your account name here" > SavedVariables
- Delete the following:
mangosbot.lua
manggosbot.lua.bak
